### ISSUE TITLE
Missing docker-stack.yml  & docker-compose.prod.yml files

### ISSUE THREAD

**Issue by valentierra** [tiangolo/full-stack-flask-couchbase#1]
I've just installed the **full-stack-flask-couchbase** and the first thing I've noticed is that there is no docker-stack.yml file. Wouldn't it be necessary to deploy the stack in production? 

Following the instructions in [https://github.com/tiangolo/full-stack/blob/master/docker-swarm-cluster-deploy.md](url), I don't know if I have to run one of the scripts to get the docker-stack.yml file, or the mentioned docker-compose.prod.yml. How would it be to deploy the stack for _full-stack-flask-couchbase_?

I'd like to deploy a small test app to verify that the frontend and backend are working in a production environment, as a little pilot before attempting more complex things

**Comment by tiangolo** [comment]
Good point! You made me realize that the docs were not clear enough.

So, I just spent a couple hours simplifying it and making it all clearer :smile:

I also separated one of the build scripts into two, so that it's easier to use it by itself.

Here's the new [`README.md` deployment section](https://github.com/tiangolo/full-stack-flask-couchbase/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md#deploy-to-a-docker-swarm-mode-cluster), it would have the contents specific to your project.

**Note**: if you want to re-generate your `README.md` for your specific project and variables, follow the [project re-generation section](https://github.com/tiangolo/full-stack-flask-couchbase/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md#project-generation-and-updating-or-re-generating).

You can see the specific changes in the docs in the commit (if you don't want to read the whole README again): https://github.com/tiangolo/full-stack-flask-couchbase/commit/ea3e9b1c9ec3d96d6a1db3d4bcf2cb03fbb5f2fa

**Comment by valentierra** [comment]
Sorry for the delay in my answer! Thank you so much Tiangolo! Impeccable as usual!

And thanks for showing so much respect by keeping this issue open. I should have closed it ages ago!

**Comment by tiangolo** [comment]
Great, thanks!
